products = [
    {"name": "Eco Water Bottle", "tags": ["eco-friendly", "durable", "recyclable"]},
    {"name": "Trail Backpack", "tags": ["durable", "water-resistant", "lightweight"]},
    {"name": "Vegan Leather Wallet", "tags": ["vegan", "stylish", "compact"]},
    {"name": "Bamboo Toothbrush", "tags": ["eco-friendly", "vegan", "biodegradable"]},
    {"name": "Smartwatch", "tags": ["tech", "durable", "stylish"]},
    {"name": "LED Desk Lamp", "tags": ["energy-efficient", "adjustable", "stylish"]},
    {"name": "Running Shoes", "tags": ["lightweight", "durable", "comfortable"]},
    {"name": "Bluetooth Speaker", "tags": ["portable", "tech", "wireless"]},
    {"name": "Portable Charger", "tags": ["tech", "travel-friendly", "reliable"]},
    {"name": "Noise-Cancelling Headphones", "tags": ["tech", "quiet", "comfortable"]},
    {"name": "Compost Bin", "tags": ["eco-friendly", "kitchen", "odor-resistant"]},
    {"name": "Yoga Mat", "tags": ["fitness", "non-slip", "lightweight"]},
    {"name": "Reusable Grocery Bags", "tags": ["eco-friendly", "reusable", "foldable"]},
    {"name": "Ergonomic Office Chair", "tags": ["comfortable", "adjustable", "supportive"]},
    {"name": "Air Purifier", "tags": ["tech", "health", "quiet"]},
    {"name": "Gaming Mouse", "tags": ["tech", "responsive", "ergonomic"]},
    {"name": "Fitness Tracker", "tags": ["tech", "fitness", "wearable"]},
    {"name": "Standing Desk", "tags": ["adjustable", "ergonomic", "modern"]},
    {"name": "Mini Projector", "tags": ["portable", "tech", "entertainment"]},
    {"name": "Cast Iron Skillet", "tags": ["durable", "kitchen", "versatile"]},
    {"name": "Electric Kettle", "tags": ["kitchen", "tech", "energy-efficient"]},
    {"name": "Foldable Bike", "tags": ["eco-friendly", "portable", "fitness"]},
    {"name": "Smart Thermostat", "tags": ["tech", "energy-efficient", "smart-home"]},
    {"name": "Wool Blanket", "tags": ["warm", "natural", "cozy"]},
    {"name": "Digital Notebook", "tags": ["tech", "reusable", "stylish"]},
    {"name": "Bamboo Cutlery Set", "tags": ["eco-friendly", "reusable", "compact"]},
    {"name": "Compact Air Fryer", "tags": ["kitchen", "tech", "compact"]},
    {"name": "Solar Phone Charger", "tags": ["eco-friendly", "tech", "travel-friendly"]},
    {"name": "Insulated Lunch Box", "tags": ["kitchen", "portable", "durable"]},
    {"name": "Smart Light Bulbs", "tags": ["tech", "energy-efficient", "smart-home"]},
    {"name": "Laptop Stand", "tags": ["tech", "ergonomic", "portable"]},
    {"name": "Electric Bike", "tags": ["eco-friendly", "tech", "fitness"]},
    {"name": "Digital Pen", "tags": ["tech", "writing", "portable"]},
    {"name": "Silicone Food Storage Bags", "tags": ["kitchen", "reusable", "eco-friendly"]},
    {"name": "UV Sanitizer Box", "tags": ["tech", "health", "compact"]},
    {"name": "Virtual Reality Headset", "tags": ["tech", "entertainment", "immersive"]},
    {"name": "Hydroponic Indoor Garden", "tags": ["eco-friendly", "tech", "kitchen"]},
    {"name": "Wireless Charging Pad", "tags": ["tech", "convenient", "modern"]},
    {"name": "Magnetic Whiteboard", "tags": ["office", "reusable", "functional"]},
    {"name": "LED String Lights", "tags": ["decor", "energy-efficient", "stylish"]},
    {"name": "Adjustable Dumbbells", "tags": ["fitness", "compact", "durable"]},
    {"name": "Weighted Blanket", "tags": ["cozy", "health", "comfortable"]},
    {"name": "Camping Stove", "tags": ["portable", "outdoors", "reliable"]},
    {"name": "Touchless Trash Can", "tags": ["kitchen", "tech", "convenient"]},
    {"name": "Electric Toothbrush", "tags": ["tech", "health", "rechargeable"]},
    {"name": "Noise Machine", "tags": ["health", "sleep", "portable"]},
    {"name": "Pet Water Fountain", "tags": ["tech", "pet", "eco-friendly"]},
    {"name": "Motion Sensor Light", "tags": ["tech", "smart-home", "safety"]},
    {"name": "Smart Door Lock", "tags": ["tech", "security", "smart-home"]},
    {"name": "Cold Brew Coffee Maker", "tags": ["kitchen", "compact", "durable"]}
]